apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app:
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodongo
        image: lightninglife/nodejs-starter:1.1
        ports:
        - containerPort: 3000
